#!/bin/bash
sudo apt-get -y install python-pip
sudo apt-get -y install git
sudo apt-get -y install python-dev
sudo apt-get -y install python-matplotlib
sudo apt-get -y  install gfortran libopenblas-dev liblapack-dev
sudo apt-get -y install cuda
sudo apt-get -y install python-pycuda
sudo apt-get -y install nvidia-current-updates 
sudo apt-get -y install python-pandas
sudo apt-get -y install nvidia-prime
sudo apt-get -y install nvidia-cuda-toolkit
sudo nvidia-xconfig
sudo pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt
sudo pip install --upgrade https://github.com/Theano/Theano/archive/master.zip
sudo pip install --upgrade  https://github.com/Lasagne/Lasagne/archive/master.zip
